### ISSUE TITLE
sync-banks.js fails if Bank Sync operation fails.

### ISSUE THREAD

**Issue by virtualJonesie** [psybers/actual-helpers#6]
Running sync-banks.js with SimpleFIN, I get the following error
```

Bank Sync operation for account: [ACCOUNT NAME REDACTED]
  Pulling transactions from SimpleFin
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Failed syncing account “[ACCOUNT NAME REDACTED]”
      at handlers.api/bank-sync (/home/dave/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29679:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} reason: Error: Failed syncing account “[ACCOUNT NAME REDACTED]”
    at handlers.api/bank-sync (/home/dave/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29679:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Failed syncing account “[ACCOUNT NAME REDACTED]”
    at handlers.api/bank-sync (/home/dave/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29679:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It appears that this is in the actual-api as opposed to your script. Would it be possible, in your script, to wrap it in a try/catch block to allow it to fail gracefully and continue syncing the rest of the accounts. As it happens today, this error kills the script.

also of note, SimpleFIN does show the authentication with this account as "Broken", and this happens with several accounts every few days, so this would add a level of resiliency to the script.

Thanks!

**Comment by psybers** [comment]
I don't think there is anything I can do here, unless I switch to calling sync one at a time on each account.  The code on my side is quite literally just `await api.runBankSync();`.  So if that throws, there is nothing to recover to... it is done.

You should report a bug on their side though.  They probably should be recovering and continuing on.
