### ISSUE TITLE
Unable to open budget due to `out-of-sync-migrations`

### ISSUE THREAD

**Issue by gmichels** [psybers/actual-helpers#8]
Hello,

I am using `actual-server:edge` (updating it daily) and trying to use the `sync-banks.js` functionality. Upon running the script, I get this error (running from within the container):

```
node@78973834f32e:/usr/src/app$ node sync-banks.js 
connect
open file
Database is out of sync with migrations: {
  appliedIds: [
    1548957970627, 1550601598648, 1555786194328,
    1561751833510, 1567699552727, 1582384163573,
    1597756566448, 1608652596043, 1608652596044,
    1612625548236, 1614782639336, 1615745967948,
    1616167010796, 1618975177358, 1632571489012,
    1679728867040, 1681115033845, 1682974838138,
    1685007876842, 1686139660866, 1688749527273,
    1688841238000, 1691233396000, 1694438752000,
    1697046240000, 1704572023730, 1704572023731,
    1707267033000, 1712784523000, 1716359441000,
    1720310586000, 1720664867241, 1720665000000,
    1722717601000, 1722804019000
  ],
  available: [
    '1548957970627_remove-db-version.sql',
    '1550601598648_payees.sql',
    '1555786194328_remove_category_group_unique.sql',
    '1561751833510_indexes.sql',
    '1567699552727_budget.sql',
    '1582384163573_cleared.sql',
    '1597756566448_rules.sql',
    '1608652596043_parent_field.sql',
    '1608652596044_trans_views.sql',
    '1612625548236_optimize.sql',
    '1614782639336_trans_views2.sql',
    '1615745967948_meta.sql',
    '1616167010796_accounts_order.sql',
    '1618975177358_schedules.sql',
    '1632571489012_remove_cache.js',
    '1679728867040_rules_conditions.sql',
    '1681115033845_add_schedule_name.sql',
    '1682974838138_remove_payee_rules.sql',
    '1685007876842_add_category_hidden.sql',
    '1686139660866_remove_account_type.sql',
    '1688749527273_transaction_filters.sql',
    '1688841238000_add_account_type.sql',
    '1691233396000_add_schedule_next_date_tombstone.sql',
    '1694438752000_add_goal_targets.sql',
    '1697046240000_add_reconciled.sql',
    '1704572023730_add_account_sync_source.sql',
    '1704572023731_add_missing_goCardless_sync_source.sql',
    '1707267033000_reports.sql',
    '1712784523000_unhide_input_group.sql',
    '1716359441000_include_current.sql',
    '1720310586000_link_transfer_schedules.sql',
    '1720664867241_add_payee_favorite.sql',
    '1720665000000_goal_context.sql'
  ]
}
Error updating Error: out-of-sync-migrations
    at checkDatabaseValidity (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39631:31)
    at Module.migrate (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39639:17)
    at async runMigrations (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43510:17)
    at async updateVersion (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43529:17)
    at async loadBudget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39254:21)
    at async handlers.load-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39084:29)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29637:21)
TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42849:98)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42761:38
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43707:38
    at initialFullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42747:38)
    at handlers.sync-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39069:94)
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29640:65)
[Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42849:98)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42761:38
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43707:38
    at initialFullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42747:38)
    at handlers.sync-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39069:94)
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29640:65)
Unhandled Rejection at: Promise Promise {
  <rejected> Error: We had an unknown problem opening “USD-e01188d”.
      at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29642:31)
} reason: Error: We had an unknown problem opening “USD-e01188d”.
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29642:31)
Error: We had an unknown problem opening “USD-e01188d”.
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29642:31)
```

Using Actual works just fine. `USD-e01188d` is the expected budget id.

Any clues on what could be the issue?

Thank you

**Comment by psybers** [comment]
You need to probably update your library: `npm update`.  And possibly remove your `cache` folder (and make an empty one after you remove it).

**Comment by gmichels** [comment]
This was on a newly-built image, but even after trying to update/cleaning up everything, I still get the same error:

```
node@78973834f32e:/usr/src/app$ npm update
|(node:141) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

up to date, audited 95 packages in 6s

16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
node@78973834f32e:/usr/src/app$ ls -l ./cache/
total 0
node@78973834f32e:/usr/src/app$ node sync-banks.js 
connect
open file
Database is out of sync with migrations: {
  appliedIds: [
    1548957970627, 1550601598648, 1555786194328,
    1561751833510, 1567699552727, 1582384163573,
    1597756566448, 1608652596043, 1608652596044,
    1612625548236, 1614782639336, 1615745967948,
    1616167010796, 1618975177358, 1632571489012,
    1679728867040, 1681115033845, 1682974838138,
    1685007876842, 1686139660866, 1688749527273,
    1688841238000, 1691233396000, 1694438752000,
    1697046240000, 1704572023730, 1704572023731,
    1707267033000, 1712784523000, 1716359441000,
    1720310586000, 1720664867241, 1720665000000,
    1722717601000, 1722804019000
  ],
  available: [
    '1548957970627_remove-db-version.sql',
    '1550601598648_payees.sql',
    '1555786194328_remove_category_group_unique.sql',
    '1561751833510_indexes.sql',
    '1567699552727_budget.sql',
    '1582384163573_cleared.sql',
    '1597756566448_rules.sql',
    '1608652596043_parent_field.sql',
    '1608652596044_trans_views.sql',
    '1612625548236_optimize.sql',
    '1614782639336_trans_views2.sql',
    '1615745967948_meta.sql',
    '1616167010796_accounts_order.sql',
    '1618975177358_schedules.sql',
    '1632571489012_remove_cache.js',
    '1679728867040_rules_conditions.sql',
    '1681115033845_add_schedule_name.sql',
    '1682974838138_remove_payee_rules.sql',
    '1685007876842_add_category_hidden.sql',
    '1686139660866_remove_account_type.sql',
    '1688749527273_transaction_filters.sql',
    '1688841238000_add_account_type.sql',
    '1691233396000_add_schedule_next_date_tombstone.sql',
    '1694438752000_add_goal_targets.sql',
    '1697046240000_add_reconciled.sql',
    '1704572023730_add_account_sync_source.sql',
    '1704572023731_add_missing_goCardless_sync_source.sql',
    '1707267033000_reports.sql',
    '1712784523000_unhide_input_group.sql',
    '1716359441000_include_current.sql',
    '1720310586000_link_transfer_schedules.sql',
    '1720664867241_add_payee_favorite.sql',
    '1720665000000_goal_context.sql'
  ]
}
Error updating Error: out-of-sync-migrations
    at checkDatabaseValidity (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39631:31)
    at Module.migrate (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39639:17)
    at async runMigrations (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43510:17)
    at async updateVersion (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43529:17)
    at async loadBudget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39254:21)
    at async handlers.load-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39084:29)
    at async handlers.download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39054:17)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29647:32)
TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42849:98)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42761:38
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43707:38
    at initialFullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42747:38)
    at handlers.sync-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39069:94)
    at handlers.download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39057:55)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29647:32)
[Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42849:98)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42761:38
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43707:38
    at initialFullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42747:38)
    at handlers.sync-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39069:94)
    at handlers.download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:39057:55)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29647:32)
Full error details {
  message: "Cannot read properties of undefined (reading 'timestamp')",
  reason: undefined,
  meta: undefined
}
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
      at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29652:27)
} reason: Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29652:27)
Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:29652:27)
node@78973834f32e:/usr/src/app$ 
```

**Comment by psybers** [comment]
Ok but again this is just a sync issue with the API.  So your only resolve is to ensure your API version matches the server's API version, and remove your local cache.
