### ISSUE TITLE
Unhandled Rejection at: Promise Promise when running kbb.js

### ISSUE THREAD

**Issue by billys09** [psybers/actual-helpers#9]
Started getting the following error when trying to pull information from Kelly Blue Book. I'm having no issues with the other services

Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:16289:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async getKBB (/opt/actual-helpers/kbb.js:9:20)
      at async /opt/actual-helpers/kbb.js:54:21 {
    cause: Error: connect ECONNREFUSED 0.0.0.0:443
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '0.0.0.0',
      port: 443

**Comment by psybers** [comment]
This is not an issue with the script. Note the log stating the address is `0.0.0.0`.  There is a problem with your network you need to figure out.  Firewall, VPN, etc.
